# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.6'

gem 'bcrypt', '~> 3.1'
gem 'puma', '~> 6.0'
gem 'rails', '~> 7.1.0'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.6'

gem 'minitest'
gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'tapioca', '~> 0.17.0', require: false, group: :development
